# Generated by Django 5.0.4 on 2024-11-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название запроса"),
                ),
                ("domen_name", models.CharField(max_length=100, verbose_name="Домен")),
                (
                    "file_html",
                    models.FileField(
                        upload_to="hosting/html/%Y/%m/%d/", verbose_name="HTML файл"
                    ),
                ),
                (
                    "file_css",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="hosting/css/%Y/%m/%d/",
                        verbose_name="CSS файл",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="Статс заявки"),
                ),
            ],
            options={
                "verbose_name": "Hosting",
                "verbose_name_plural": "Hostings",
                "ordering": ["-status"],
            },
        ),
    ]
