# Generated by Django 5.1.3 on 2024-11-17 19:56

import Hosting.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название запроса"),
                ),
                ("domen_name", models.CharField(max_length=100, verbose_name="Домен")),
                (
                    "file_html",
                    models.FileField(
                        upload_to=Hosting.models.upload_to_domen,
                        verbose_name="HTML файл",
                    ),
                ),
                (
                    "file_css",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=Hosting.models.upload_to_domen,
                        verbose_name="CSS файл",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="Статс заявки"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hosting",
                "verbose_name_plural": "Hostings",
                "ordering": ["-status"],
            },
        ),
    ]
